Repository jakeheft/crate, pull requests merged in 2021-02, with the labels that each got.

#30 Product images
  code/web/package-lock.json
  code/web/package.json
  code/web/public/images/stock/men/accessories-male-1.jpg
  code/web/public/images/stock/men/accessories-male-2.jpg
  code/web/public/images/stock/men/accessories-male-3.jpg
  code/web/public/images/stock/men/pants-male-1.jpg
  code/web/public/images/stock/men/pants-male-2.jpg
  code/web/public/images/stock/men/pants-male-3.jpg
  code/web/public/images/stock/men/shirt-male-3.jpg
  code/web/public/images/stock/men/shirt-male-4.jpg
  code/web/public/images/stock/men/shirt-male-5.jpg
  code/web/public/images/stock/men/shoes-male-1.jpg
  code/web/public/images/stock/men/shoes-male-2.jpg
  code/web/public/images/stock/men/shoes-male-3.jpg
  code/web/public/images/stock/women/accessories-female-1.jpg
  code/web/public/images/stock/women/accessories-female-2.jpg
  code/web/public/images/stock/women/accessories-female-3.jpg
  code/web/public/images/stock/women/pants-female-1.jpg
  code/web/public/images/stock/women/pants-female-2.jpg
  code/web/public/images/stock/women/shirt-female-3.jpg
  code/web/public/images/stock/women/shirt-female-4.jpg
  code/web/public/images/stock/women/shirt-female-5.jpg
  code/web/public/images/stock/women/shoes-female-1.jpg
  code/web/public/images/stock/women/shoes-female-2.jpg
  code/web/public/images/stock/women/shoes-female-3.jpg
  code/web/public/images/stock/women/skirt-female-3.jpg
  code/web/src/setup/store.js
  package-lock.json
  package.json
Labels: enhancement, front end, project-setup

#29 addStyle with mutation, resolver, mutation and tests
  code/api/package-lock.json
  code/api/package.json
  code/api/src/config/database.json
  code/api/src/migrations/5-user_style.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/api/src/modules/user/tests/userMutation.test.js
  code/api/src/modules/user/tests/userQuery.test.js
  code/api/src/modules/user/types.js
Labels: TDD, back end

#40 Feature/action
  code/web/src/modules/user/StylePreferences.js
  code/web/src/modules/user/api/actions.js
Labels: MVP

#45 Feature/modal and styling
  code/api/package-lock.json
  code/web/src/modules/crate/Item.js
  code/web/src/modules/user/StylePreferences.js
  code/web/src/modules/user/SurveyCards.js
Labels: enhancement, front end

#48 Feature/fix testing
  code/web/.DS_Store
  code/web/cypress.json
  code/web/cypress/.DS_Store
  code/web/cypress/integration/.DS_Store
  code/web/cypress/integration/examples/survey.test.js
  code/web/cypress/plugins/index.js
  code/web/cypress/support/commands.js
  code/web/cypress/support/index.js
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/StylePreferences.js
  code/web/src/modules/user/SurveyCards.js
  code/web/src/modules/user/tests/POST.test.js
  code/web/src/modules/user/tests/StylePreferences.test.js
  code/web/src/modules/user/tests/SurveyCards.test.js
Labels: MVP, enhancement, front end
